name: Rename default branch

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  rename:
    runs-on: ubuntu-24.04
    steps:
      - name: Rename master to main
        env:
          GH_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
        run: |
          gh api --method POST "repos/${REPOSITORY}/branches/master/rename" -f new_name=main
